#!/usr/bin/env bash

backup() {
  echo "Doing backup, buddy"
  # Neovim
  if [ -d $HOME/.config/nvim ]; then
    mv $HOME/.config/nvim{,.old}
  fi

  # Alacritty
  if [ -d $HOME/.config/alacritty ]; then
    mv $HOME/.config/alacritty{,.old}
  fi

  # Tmux
  if [ -d $HOME/.tmux ]; then
    mv $HOME/.tmux{,.old}
  fi

  if [ -f $HOME/.tmux.conf ]; then
    mv $HOME/.tmux.conf{,.old}
  fi

  if [ -f $HOME/.zshrc ]; then
    mv $HOME/.zshrc{,.old}
  fi
}

neovim() {
  ln -sf $(pwd)/nvim $HOME/.config/nvim
}

zshrc() {
  ln -sf $(pwd)/zsh/zshrc $HOME/.zshrc
}

tmux() {
  ln -sf $(pwd)/tmux.conf $HOME/.tmux.conf
}

kitty() {
  ln -sf $(pwd)/kitty $HOME/.config/kitty
}

backup
neovim
tmux
kitty
zshrc
